"""Agent-facing instruction files — one protocol, many formats.

Different coding agents look for their own instruction file in their own place
and (sometimes) wrap it in their own frontmatter. Rather than maintain N copies
that drift, this module keeps ONE canonical retrieval protocol (`_protocol_body`)
and renders it through a small registry of per-agent adapters. Adding or fixing a
convention is a one-entry change in `TARGETS`, not a rewrite — which matters
because these conventions change often.

Conventions targeted (verify against current vendor docs; noted per adapter):

* **GitHub Copilot, repo-wide** — `.github/copilot-instructions.md`, plain
  markdown, auto-applied to every Copilot chat in the repo.
* **GitHub Copilot, path-scoped** — `.github/instructions/*.instructions.md`
  with an `applyTo:` glob in YAML frontmatter. We emit one with `applyTo: "**"`.
* **OpenAI Codex / agents.md ecosystem** — `AGENTS.md` at the repo root, plain
  markdown (Codex also merges nested AGENTS.md; Cursor/Jules/Factory read it too).
* **Cursor project rules** — `.cursor/rules/*.mdc`, MDC frontmatter
  (`description`, `globs`, `alwaysApply`).
* **Claude Code** — `CLAUDE.md` at the repo root, plain markdown.

Every adapter is a pure function returning file text, so the whole set is
testable by string assertions with no I/O.
"""

from __future__ import annotations

from collections.abc import Callable
from dataclasses import dataclass

from work_kb.models import Tier

_GENERATED_BANNER = "<!-- GENERATED by `kb build` — do not edit by hand. -->"

Counts = dict[Tier, int]


def _protocol_body(counts: Counts, *, agent_name: str = "your agent") -> str:
    """The canonical, agent-neutral retrieval protocol. Every instruction file
    is this body plus a format-specific wrapper. `agent_name` only personalizes
    one sentence (e.g. 'VS Code Copilot' vs 'Codex')."""
    return (
        "# Working with this knowledge base\n\n"
        "This workspace contains a three-tier knowledge base under `kb/`. "
        f"When answering project questions, {agent_name} should consult it "
        "first, using the cheapest tier that can answer.\n\n"
        "## Retrieval protocol\n\n"
        f"1. **Foundation** ({counts[Tier.FOUNDATION]} items) — read "
        "`kb/00-foundation/INDEX.md` first. It is small and always relevant; "
        "read the whole thing.\n"
        f"2. **Details** ({counts[Tier.DETAIL]} items) — for specifics, open "
        "`kb/10-details/INDEX.md` (a topic map), pick a topic, then open only "
        "the linked items you need. Do not load the whole tier.\n"
        f"3. **Artifacts** ({counts[Tier.ARTIFACT]} items) — for notes, "
        "snippets, and logs, SEARCH `kb/20-artifacts/items/` with your "
        "file-search tool. This tier is not enumerated; find by keyword or by "
        "frontmatter (`project:`, `tags:`).\n\n"
        "## Item format\n\n"
        "Every item is a markdown file with YAML frontmatter: `slug`, `tier`, "
        "`title`, optional `tags`, `project`, `created`, and `links` "
        "(cross-references to other items by slug). Prefer items whose "
        "`project` or `tags` match the question.\n\n"
        "## Machine-readable index\n\n"
        "`kb/index.json` is a structured catalog of the whole KB (tiers, item "
        "paths, topic and project clusters). Read it when you want to enumerate "
        "or filter programmatically instead of browsing the markdown.\n"
    )


def _plain(counts: Counts, agent_name: str) -> str:
    return f"{_GENERATED_BANNER}\n\n{_protocol_body(counts, agent_name=agent_name)}"


def render_copilot_repo(counts: Counts) -> str:
    """GitHub Copilot, repo-wide. Plain markdown; no frontmatter."""
    return _plain(counts, "VS Code Copilot")


def render_copilot_pathscoped(counts: Counts) -> str:
    """GitHub Copilot path-scoped instruction. YAML frontmatter `applyTo` glob;
    `**` attaches it to every file so it behaves like a repo-wide rule while
    living in the `.github/instructions/` mechanism some setups prefer."""
    return (
        "---\n"
        'applyTo: "**"\n'
        "---\n"
        f"{_GENERATED_BANNER}\n\n"
        f"{_protocol_body(counts, agent_name='Copilot')}"
    )


def render_agents_md(counts: Counts) -> str:
    """AGENTS.md — OpenAI Codex and the broader agents.md ecosystem
    (Cursor, Jules, Factory, …). Plain markdown."""
    return _plain(counts, "the agent")


def render_claude_md(counts: Counts) -> str:
    """CLAUDE.md — Claude Code reads this at the repo root."""
    return _plain(counts, "Claude")


def render_cursor_mdc(counts: Counts) -> str:
    """Cursor project rule (.mdc). MDC frontmatter; `alwaysApply: true` makes it
    a global rule rather than glob-scoped."""
    return (
        "---\n"
        "description: Project knowledge base — three-tier retrieval protocol\n"
        "globs:\n"
        "alwaysApply: true\n"
        "---\n"
        f"{_GENERATED_BANNER}\n\n"
        f"{_protocol_body(counts, agent_name='Cursor')}"
    )


@dataclass(frozen=True)
class Target:
    """One agent convention: where its file goes and how to render it."""

    path: str
    render: Callable[[Counts], str]
    note: str


# The registry. Add a convention here and `kb build` emits it everywhere.
TARGETS: list[Target] = [
    Target(".github/copilot-instructions.md", render_copilot_repo, "GitHub Copilot (repo-wide)"),
    Target(
        ".github/instructions/knowledge-base.instructions.md",
        render_copilot_pathscoped,
        "GitHub Copilot (path-scoped, applyTo)",
    ),
    Target("AGENTS.md", render_agents_md, "OpenAI Codex + agents.md ecosystem"),
    Target("CLAUDE.md", render_claude_md, "Claude Code"),
    Target(".cursor/rules/knowledge-base.mdc", render_cursor_mdc, "Cursor project rule"),
]


def render_agent_files(counts: Counts) -> dict[str, str]:
    """All agent instruction files keyed by repo-relative path."""
    return {t.path: t.render(counts) for t in TARGETS}
