"""The compiler core — pure: a set of items in, a set of generated files out.

No I/O lives here, so the whole build is unit-testable by asserting on returned
strings. ``build(items)`` returns ``{repo_relative_path: content}``; the store
writes them. Each tier renders to the navigation shape that matches its size:
foundation enumerates, detail maps by topic, artifacts only report stats (their
retrieval is grep, not a generated index).
"""

from __future__ import annotations

from collections import defaultdict

from work_kb.models import Item, Tier, shard

_GENERATED_BANNER = "<!-- GENERATED by `kb build` — do not edit by hand. -->"


def _by_tier(items: list[Item]) -> dict[Tier, list[Item]]:
    out: dict[Tier, list[Item]] = {t: [] for t in Tier}
    for it in items:
        out[it.tier].append(it)
    for t in out:
        out[t].sort(key=lambda i: (i.title.lower(), i.slug))
    return out


def _rel_item_path(item: Item) -> str:
    """The path to an item file, relative to the kb/ dir, for use in links."""
    sub = "items"
    if item.tier in (Tier.DETAIL, Tier.ARTIFACT):
        sub = f"items/{shard(item.slug)}"
    return f"{item.tier.dirname}/{sub}/{item.slug}.md"


def render_foundation_index(items: list[Item]) -> str:
    """Tier 1: enumerate every item inline. This file is meant to be read whole
    by the agent, so it carries the titles (and one-line bodies, if short)."""
    lines = [_GENERATED_BANNER, "", "# Foundation — core project facts", ""]
    if not items:
        lines.append("_No foundational items yet._")
        return "\n".join(lines) + "\n"
    lines.append(f"_{len(items)} items. Always relevant — read this whole file._")
    lines.append("")
    for it in items:
        rel = f"items/{it.slug}.md"
        tags = f"  ·  _{', '.join(it.tags)}_" if it.tags else ""
        lines.append(f"- **[{it.title}]({rel})**{tags}")
    return "\n".join(lines) + "\n"


def render_detail_index(items: list[Item]) -> str:
    """Tier 2: a navigable *map*, not a flat list of 10k. Group by tag so the
    agent picks a topic and drills into ``by-tag/<tag>.md``."""
    lines = [_GENERATED_BANNER, "", "# Details — pull on demand", ""]
    if not items:
        lines.append("_No detail items yet._")
        return "\n".join(lines) + "\n"

    by_tag: dict[str, int] = defaultdict(int)
    untagged = 0
    for it in items:
        if it.tags:
            for tag in it.tags:
                by_tag[tag] += 1
        else:
            untagged += 1

    lines.append(
        f"_{len(items)} items across {len(by_tag)} topics. "
        "Pick a topic, open its page, then open only the items you need._"
    )
    lines.append("")
    lines.append("## Topics")
    for tag in sorted(by_tag):
        lines.append(f"- [{tag}](by-tag/{tag}.md) ({by_tag[tag]})")
    if untagged:
        lines.append(f"- _(untagged: {untagged} — these are only findable by search)_")
    return "\n".join(lines) + "\n"


def render_tag_pages(items: list[Item]) -> dict[str, str]:
    """One page per tag listing its detail items, with links up to the item
    files. Keyed by the kb-relative path."""
    grouped: dict[str, list[Item]] = defaultdict(list)
    for it in items:
        for tag in it.tags:
            grouped[tag].append(it)

    pages: dict[str, str] = {}
    for tag, tag_items in grouped.items():
        tag_items.sort(key=lambda i: (i.title.lower(), i.slug))
        lines = [_GENERATED_BANNER, "", f"# {tag}", "", f"_{len(tag_items)} items._", ""]
        for it in tag_items:
            rel = f"items/{shard(it.slug)}/{it.slug}.md"
            proj = f"  ·  _{it.project}_" if it.project else ""
            lines.append(f"- **[{it.title}]({rel})**{proj}")
        pages[f"{Tier.DETAIL.dirname}/by-tag/{tag}.md"] = "\n".join(lines) + "\n"
    return pages


def render_artifact_manifest(items: list[Item]) -> str:
    """Tier 3: stats only. Retrieval is grep, so we deliberately do NOT
    enumerate 50k files — we tell the agent how to search them."""
    lines = [_GENERATED_BANNER, "", "# Artifacts — searchable archive", ""]
    lines.append(f"_{len(items)} items. NOT enumerated — search this tier._")
    lines.append("")
    if items:
        tags: dict[str, int] = defaultdict(int)
        projects: dict[str, int] = defaultdict(int)
        for it in items:
            for tag in it.tags:
                tags[tag] += 1
            if it.project:
                projects[it.project] += 1
        lines.append("## How to find things here")
        lines.append("Use your file-search tool over `kb/20-artifacts/items/`:")
        lines.append("- by keyword in the body, or")
        lines.append("- by frontmatter field, e.g. `project: <name>` or `tags:`.")
        lines.append("")
        if projects:
            lines.append("## Projects present")
            for p in sorted(projects):
                lines.append(f"- {p} ({projects[p]})")
            lines.append("")
        if tags:
            lines.append("## Tags present")
            lines.append(", ".join(f"`{t}` ({tags[t]})" for t in sorted(tags)))
    return "\n".join(lines) + "\n"


def render_copilot_instructions(counts: dict[Tier, int]) -> str:
    """The integration surface. VS Code Copilot auto-loads this file for the
    workspace; it teaches the agent the three-tier retrieval protocol. No
    service, no admin — just a file."""
    return (
        f"{_GENERATED_BANNER}\n\n"
        "# Working with this knowledge base\n\n"
        "This workspace contains a three-tier knowledge base under `kb/`. "
        "Consult it before answering project questions, using the cheapest tier "
        "that can answer.\n\n"
        "## Retrieval protocol\n\n"
        f"1. **Foundation** ({counts[Tier.FOUNDATION]} items) — read "
        "`kb/00-foundation/INDEX.md` first. It is small and always relevant; "
        "read the whole thing.\n"
        f"2. **Details** ({counts[Tier.DETAIL]} items) — for specifics, open "
        "`kb/10-details/INDEX.md` (a topic map), pick a topic, then open only "
        "the linked items you need. Do not load the whole tier.\n"
        f"3. **Artifacts** ({counts[Tier.ARTIFACT]} items) — for notes, "
        "snippets, and logs, SEARCH `kb/20-artifacts/items/` with your "
        "file-search tool. This tier is not enumerated; find by keyword or by "
        "frontmatter (`project:`, `tags:`).\n\n"
        "## Item format\n\n"
        "Every item is a markdown file with YAML frontmatter: `slug`, `tier`, "
        "`title`, optional `tags`, `project`, `created`, and `links` "
        "(cross-references to other items by slug). Prefer items whose "
        "`project` or `tags` match the question.\n"
    )


def render_agents_md(counts: dict[Tier, int]) -> str:
    """Vendor-neutral twin of the Copilot file, for any other file-reading
    agent (Claude, Cursor, …) that looks for AGENTS.md."""
    body = render_copilot_instructions(counts)
    return body.replace("VS Code Copilot", "your agent", 1)


def build(items: list[Item]) -> dict[str, str]:
    """Pure compiler: items -> {repo-relative path: file content}."""
    tiers = _by_tier(items)
    counts = {t: len(tiers[t]) for t in Tier}

    files: dict[str, str] = {
        f"kb/{Tier.FOUNDATION.dirname}/INDEX.md": render_foundation_index(tiers[Tier.FOUNDATION]),
        f"kb/{Tier.DETAIL.dirname}/INDEX.md": render_detail_index(tiers[Tier.DETAIL]),
        f"kb/{Tier.ARTIFACT.dirname}/MANIFEST.md": render_artifact_manifest(tiers[Tier.ARTIFACT]),
        ".github/copilot-instructions.md": render_copilot_instructions(counts),
        "AGENTS.md": render_agents_md(counts),
    }
    for relpath, content in render_tag_pages(tiers[Tier.DETAIL]).items():
        files[f"kb/{relpath}"] = content
    return files
